from cryptography.fernet import Fernet
key = Fernet.generate_key()
cipher = Fernet(key)
data = input("Enter text to encrypt: ").encode()
encrypted_data = cipher.encrypt(data)
print("\n Encrypted text:", encrypted_data.decode())
decrypted_data = cipher.decrypt(encrypted_data)
print(" Decrypted text:", decrypted_data.decode())
print("\nKeep this secret key safe if you want to decrypt later:")
print(key.decode())
